'''
if :
     In program to run some lines of code at specific condition we can use "if"
     If condition is true then only it run that lines if code 
        
        Syntax:
               .......code......
               .......code......
               if (condition):                          # () is optional but standard way is by not using (). 
                            ...........code.......      # we have to give some space after if. standard way is to give 4 spaces or to give tab
                            ...........code.......
                            ...........code.......
               .......code......
               .......code......
'''

print("This is program to know about if")
a=3
b=20
if a==3:
        print("We are in a as condition is true")
print("We can use another if to check false condition")
if b==5:
        print("We are in b as condition is true")
print("As in above second condition is false so it will not print b")


'''
if else:
        We can use 'if' to execute code for conditon is true and we can use 'else' to execute code for condition is false. 
        
        Syntax: 
               .......code......
               .......code......
               if (condition):                          # () is optional but standard way is by not using (). 
                            ...........code.......      # we have to give some space after if. standard way is to give 4 spaces or to give tab
                            ...........code.......
                            ...........code.......
               else:
                            ...........code.......
                            ...........code.......
                            ...........code.......
               .......code......
               .......code......
'''

print("This is program to know about if else")
a=30
if a==3:
        print("We are in if as condition is true")
else:
        print("We are in else as condition is false")
print("As in above if condition is false it will print else")

'''
if elif:
        If there is more than 1 condition to check then we can use elif 
         Syntax: 
               .......code......
               .......code......
               if (condition):                          # () is optional but standard way is by not using (). 
                            ...........code.......      # we have to give some space after if. standard way is to give 4 spaces or to give tab
                            ...........code.......
                            ...........code.......
               elif condition:
                            ...........code.......
                            ...........code.......
                            ...........code.......
               elif condition:
                            ...........code.......
                            ...........code.......
                            ...........code.......
               else:
                            ...........code.......
                            ...........code.......
                            ...........code.......
               .......code......
               .......code......
'''

print("This is program to know about if else")
a=30
if a>70:
        print("Distinction")
elif a>50 and a<70:
        print("First class")
elif a>35 and a<50:
        print("Second class") 
else:
        print("fail")
print("It checks multiple condition")
